2017-07-19 16:59:35.6517|0|Chloe.Admin.Controllers.AccountController.Login (Chloe.Admin)|ERROR|  Error: SQLite Error 14: 'unable to open database file'.,    at Microsoft.Data.Sqlite.Interop.MarshalEx.ThrowExceptionForRC(Int32 rc, Sqlite3Handle db)#R##N#   at Microsoft.Data.Sqlite.SqliteConnection.Open()#R##N#   at Chloe.Core.InternalAdoSession.ExecuteReader(String cmdText, DbParam[] parameters, CommandType cmdType, CommandBehavior behavior)#R##N#   at Chloe.Query.Internals.QueryEnumeratorCreator.QueryEnumerator`1.MoveNext()#R##N#   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)#R##N#   at Ace.Application.System.Implements.AccountAppService.CheckLogin(String userName, String password, Sys_User& user, String& msg) in D:\GitHub\Ace\src\DotNetCore\Ace.Application.System\Implements\AccountAppService.cs:line 41#R##N#   at Chloe.Admin.Controllers.AccountController.Login(String userName, String password, String verifyCode) in D:\GitHub\Ace\src\DotNetCore\Chloe.Admin\Controllers\AccountController.cs:line 53#R##N#   at lambda_method(Closure , Object , Object[] )#R##N#   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()#R##N#--- End of stack trace from previous location where exception was thrown ---#R##N#   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()#R##N#   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)#R##N#   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__25.MoveNext()#R##N#--- End of stack trace from previous location where exception was thrown ---#R##N#   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()#R##N#   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)#R##N#   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)#R##N#   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextExceptionFilterAsync>d__24.MoveNext() |url: http://localhost/Account/Login|action: Login
2017-07-19 17:00:26.7997|0|Chloe.Admin.Controllers.AccountController.Login (Chloe.Admin)|ERROR|  Error: SQLite Error 14: 'unable to open database file'.,    at Microsoft.Data.Sqlite.Interop.MarshalEx.ThrowExceptionForRC(Int32 rc, Sqlite3Handle db)#R##N#   at Microsoft.Data.Sqlite.SqliteConnection.Open()#R##N#   at Chloe.Core.InternalAdoSession.ExecuteReader(String cmdText, DbParam[] parameters, CommandType cmdType, CommandBehavior behavior)#R##N#   at Chloe.Query.Internals.QueryEnumeratorCreator.QueryEnumerator`1.MoveNext()#R##N#   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)#R##N#   at Ace.Application.System.Implements.AccountAppService.CheckLogin(String userName, String password, Sys_User& user, String& msg) in D:\GitHub\Ace\src\DotNetCore\Ace.Application.System\Implements\AccountAppService.cs:line 41#R##N#   at Chloe.Admin.Controllers.AccountController.Login(String userName, String password, String verifyCode) in D:\GitHub\Ace\src\DotNetCore\Chloe.Admin\Controllers\AccountController.cs:line 53#R##N#   at lambda_method(Closure , Object , Object[] )#R##N#   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()#R##N#--- End of stack trace from previous location where exception was thrown ---#R##N#   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()#R##N#   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)#R##N#   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__25.MoveNext()#R##N#--- End of stack trace from previous location where exception was thrown ---#R##N#   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()#R##N#   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)#R##N#   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)#R##N#   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextExceptionFilterAsync>d__24.MoveNext() |url: http://localhost/Account/Login|action: Login
